<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SearchButtonClick</description>
   <name>GoogleSearchButton</name>
   <tag></tag>
   <elementGuidId>397fb6d0-7bdb-490f-b894-11970eef0d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnK</value>
   </webElementProperties>
</WebElementEntity>
