<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AgentQuoteBtn</name>
   <tag></tag>
   <elementGuidId>b84ee68b-a5ef-460f-9965-2a182a3f5ddb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-button__ripple-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AjaxBody&quot;)/div[@class=&quot;mdl-grid mdl-grid--no-spacing dashboard-lead js-dashboard-lead&quot;]/div[@class=&quot;mdl-cell mdl-cell--4-col-phone mdl-cell--8-col-tablet mdl-cell--2-col&quot;]/div[@class=&quot;mdl-card custom-card dashboard-lead-card mdl-shadow--2dp&quot;]/div[@class=&quot;mdl-card__supporting-text&quot;]/button[@class=&quot;mdl-button mdl-js-button mdl-js-ripple-effect lowercase mdl-shadow--2dp&quot;]/span[@class=&quot;mdl-button__ripple-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
